# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # 기본 코드 품질 체크
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|mdx)$
      - id: end-of-file-fixer
        exclude: \.(md|mdx)$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: mixed-line-ending
        args: ['--fix=lf']

  # TypeScript/JavaScript 린팅 및 포맷팅
  - repo: local
    hooks:
      # ESLint 체크 (소스 파일만)
      - id: eslint
        name: ESLint
        entry: pnpm eslint --fix --ext .js,.jsx,.ts,.tsx --max-warnings 0 src/ app/
        language: system
        files: ^(src|app)/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

      # TypeScript 타입 체크
      - id: typescript
        name: TypeScript Check
        entry: pnpm tsc --noEmit
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

      # Prettier 포맷팅
      - id: prettier
        name: Prettier
        entry: pnpm prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|json|css|md|mdx)$
